on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions: {}

name: release-please

jobs:
  release-please:
    runs-on: macos-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update Cargo.lock
        run: |
          git fetch origin release-please--branches--main--components--rmk-gui
          git checkout release-please--branches--main--components--rmk-gui
          cargo check --manifest-path src-tauri/Cargo.toml
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          if git diff --quiet src-tauri/Cargo.lock; then
            echo "No changes to Cargo.lock, skipping commit and push"
          else
            git add src-tauri/Cargo.lock
            git commit -m "chore: update Cargo.lock"
            git push origin HEAD:release-please--branches--main--components--rmk-gui
          fi

      - uses: actions/checkout@v4
        if: ${{ steps.release.outputs.release_created }}
        with:
          ref: prod

      - name: publish to prod branch
        if: ${{ steps.release.outputs.release_created }}
        run: |
          git fetch origin main
          git pull --ff-only origin main
          git remote set-url origin "https://x-access-token:${{ secrets.RMK_GUI_RELEASE_TOKEN }}@github.com/${{ github.repository }}.git"
          git push
