on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions: {}

name: release-please

jobs:
  release-please:
    runs-on: macos-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Update Cargo.lock
        run: |
          cd src-tauri
          cargo check
          git add Cargo.lock
          git commit -m "Update Cargo.lock" || echo "No changes to commit"
      
      - name: Push Cargo.lock changes
        run: |
          git push origin HEAD:${{ github.ref_name }} || echo "Nothing to push"
      
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - uses: actions/checkout@v4
        if: ${{ steps.release.outputs.release_created }}
        with:
          ref: prod
      
      - name: publish to prod branch
        if: ${{ steps.release.outputs.release_created }}
        run: |
          git fetch origin main
          git pull --ff-only origin main
          git remote set-url origin "https://x-access-token:${{ secrets.RMK_GUI_RELEASE_TOKEN }}@github.com/${{ github.repository }}.git"
          git push